export CXX="/usr/bin/clang"
export CXXFLAGS="-std=c++11"
export CPPFLAGS="-std=c++11"
set ROTPY_INCLUDE="C:\Program Files\FLIR\Spinnaker\include"
set ROTPY_LIB="C:\Program Files\FLIR\Spinnaker\bin64\vs2015;C:\Program Files\FLIR\Spinnaker\lib64\vs2015"